# Code generated by font_to_py.py.
# Font: msyh.ttf Char set: .中听聆
# Cmd: D:\code\esp32-s3-project\.venv\Scripts\font_to_py .\font\msyh.ttf 12 msyh.py -c 聆听中.
version = '0.42'

def height():
    return 12

def baseline():
    return 10

def max_width():
    return 12

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 46

def max_ch():
    return 32838

_font =\
b'\x06\x00\x00\x30\x48\x08\x08\x10\x20\x20\x00\x20\x00\x00\x00\x00'\
b'\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x60\x60\x00\x00\x00\x00'\
b'\x06\x00\x00\x30\x48\x08\x08\x10\x20\x20\x00\x20\x00\x00\x00\x00'\
b'\x0c\x00\x06\x00\x06\x00\x7f\xe0\x46\x20\x46\x20\x46\x20\x7f\xe0'\
b'\x46\x20\x06\x00\x06\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x0c\x00\x00\x60\x73\x80\x52\x00\x52\x00\x53\xf0\x52\x40\x54\x40'\
b'\x74\x40\x44\x40\x04\x40\x08\x40\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x0c\x00\x00\x80\xf9\x80\x51\x40\x53\x40\x74\xa0\x54\x10\x77\xe0'\
b'\x50\x20\x78\x40\xd2\x80\x11\x80\x10\x40'

_sparse =\
b'\x2e\x00\x02\x00\x3f\x00\x04\x00\x2d\x4e\x06\x00\x2c\x54\x0a\x00'\
b'\x46\x80\x0e\x00'

_mvfont = memoryview(_font)
_mvsp = memoryview(_sparse)
ifb = lambda l : l[0] | (l[1] << 8)

def bs(lst, val):
    while True:
        m = (len(lst) & ~ 7) >> 1
        v = ifb(lst[m:])
        if v == val:
            return ifb(lst[m + 2:])
        if not m:
            return 0
        lst = lst[m:] if v < val else lst[:m]

def get_ch(ch):
    doff = bs(_mvsp, ord(ch)) << 3
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 12
    return _mvfont[doff + 2:next_offs], 12, width

